CREATE TABLE IF NOT EXISTS tb_produtos (
                                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           no_produto VARCHAR(100) NOT NULL,
                                           pc_taxa_juros_anual DECIMAL(12,9) NOT NULL,
                                           nu_maximo_meses INT NOT NULL,
                                           st_ativo BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS tb_simulacao (
                                            nu_simulacao BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            id_produto BIGINT NOT NULL,
                                            vr_simulacao DECIMAL(18,2) NOT NULL,
                                            pr_simulacao INT NOT NULL,
                                            vr_total DECIMAL(18,2),
                                            vr_parcela DECIMAL(18,2),
                                            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                            FOREIGN KEY (id_produto) REFERENCES tb_produtos(id)
);

CREATE TABLE IF NOT EXISTS tb_parcelas (
                                           id_parcela BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           nu_simulacao BIGINT NOT NULL,
                                           numero_parcela INT NOT NULL,
                                           saldo_devedor DECIMAL(18,2) NOT NULL,
                                           juros DECIMAL(18,2) NOT NULL,
                                           valor_parcela DECIMAL(18,2) NOT NULL,
                                           FOREIGN KEY (nu_simulacao) REFERENCES tb_simulacao(nu_simulacao)
);