CREATE TABLE IF NOT EXISTS tb_produtos (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             no_produto VARCHAR(100) NOT NULL,
                             pc_taxa_juros_anual DECIMAL(12,9) NOT NULL,
                             nu_maximo_meses INT NOT NULL,
                             st_ativo BOOLEAN NOT NULL
);